import java.util.*;
import java.nio.charset.*;

public class GameWord {

    public static String autoGeneratedString(int length){
    
        // length is bounded by 256 Character
        byte[] array = new byte[256];
        new Random().nextBytes(array);
        String randomString = new String(array, Charset.forName("UTF-8"));
    
        // Create a StringBuffer to store the result
        StringBuffer r = new StringBuffer();
    
        // Append first 20 characters
        // from the generated random String into the result
    
        for (int k = 0; k < randomString.length(); k++) {
            char ch = randomString.charAt(k);
      
            if ((ch >= 'A' && ch <= 'Z') && (length > 0)) {
        
            r.append(ch);
            length--;
            }
        }
        // return the resultant string
        return r.toString();
    }

    public static char[] gameWord(){
        return autoGeneratedString(8).toCharArray();
    }
}